### ISSUE TITLE
no module named 'torch' / no module named 'hallo' tripped by inference.py line 39

### ISSUE THREAD

**Issue by CPavlis** [fudan-generative-vision/hallo#118]
Everything went fine except installing xformers which for some reason spits out "no module named torch" dispite torch pytoch torchvision and I think a couple others installed.  I tried installing xformers with --no-dependencies but it spit out the same...

update: very similar to https://github.com/facebookresearch/xformers/issues/740 
update: pip install wheels solved this!

so I tried anyway to run python3 scripts/inference.py without any command line just to see if it would spit out some errors, as I don't have a .wav or pic formatted yet, and was surprised it couldn't find hallo

anyone have any ideas for this issue? (I should probably mention this is in a venv)

**Comment by AricGamma** [comment]
After installed wheels, please try re-install this project as a package by `pip install .`

**Comment by CPavlis** [comment]
after wheels was installed pip install xformers still failed but this time with "nvcc exited with code 255" (the rest made little sense, seemed to imply a missing bracket)

pip install . was something I remember reading a few times but never tried - noob mistake? problem with self-teaching, now i know, thanks. - I note while it was running it downloaded nvidia_nccl, torch and torchvision - but produced the same ending

/ai/hallo/lib/python3.12/site-packages/torch/include/ATen/core/boxing/impl/boxing.h:42:106: error: expected primary-expression before ‘)’ token
         42 | struct has_ivalue_to<T, std::void_t<decltype(std::declval<IValue>().to<T>())>>
            |                                                                                                          ^
      error: command '/usr/local/cuda/bin/nvcc' failed with exit code 255
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xformers
  Running setup.py clean for xformers
Successfully built hallo
Failed to build xformers
