### ISSUE TITLE
Everything is working fine, but why does the inferred video file have no sound, only lip movements?

### ISSUE THREAD

**Issue by kellyzxiaowei** [fudan-generative-vision/hallo#13]
100% 2/2 [00:04<00:00,  2.48s/it]
100% 2/2 [00:00<00:00,  9.86it/s]
2024-06-15 19:03:42,073 - INFO - mdx_separator - Saving Vocals stem to aud_1_(Vocals)_Kim_Vocal_2.wav...
2024-06-15 19:03:42,377 - INFO - common_separator - Clearing input audio file paths, sources and stems...
2024-06-15 19:03:42,377 - INFO - separator - Separation duration: 00:00:06
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel: 
 ['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from pretrained_models/motion_module/mm_sd_v15_v2.ckpt
loaded weight from  ./pretrained_models/hallo/net.pth
100% 40/40 [00:25<00:00,  1.55it/s]
100% 16/16 [00:00<00:00, 30.32it/s]
100% 40/40 [00:25<00:00,  1.57it/s]
100% 16/16 [00:00<00:00, 32.29it/s]
100% 40/40 [00:25<00:00,  1.57it/s]
100% 16/16 [00:00<00:00, 32.26it/s]
100% 40/40 [00:25<00:00,  1.56it/s]
100% 16/16 [00:00<00:00, 32.27it/s]
100% 40/40 [00:25<00:00,  1.56it/s]
100% 16/16 [00:00<00:00, 32.26it/s]
100% 40/40 [00:25<00:00,  1.56it/s]
100% 16/16 [00:00<00:00, 32.25it/s]
100% 40/40 [00:25<00:00,  1.56it/s]
100% 16/16 [00:00<00:00, 32.23it/s]
Moviepy - Building video /content/output1.mp4.
MoviePy - Writing audio in output1TEMP_MPY_wvf_snd.mp3
MoviePy - Done.
Moviepy - Writing video /content/output1.mp4

Moviepy - Done !
Moviepy - video ready /content/output1.mp4

**Comment by daswer123** [comment]
Hello , When I was testing, I have an output with sound.

**Comment by subazinga** [comment]
Some video players such as the video preview of MacOS can not play the sound. You can try VLC, INNA.

**Comment by AricGamma** [comment]
Closing this issue. If you have other questions, please open a new one.
