### ISSUE TITLE
Issue with xformers

### ISSUE THREAD

**Issue by roudimit** [fudan-generative-vision/hallo#131]
Hi! Does the inference speed depend on xformers being correctly installed?

I created the conda environment / pip install. When I ran the inference code: `python scripts/inference.py --source_image examples/reference_images/1.jpg --driving_audio examples/driving_audios/1.wav` the code works but is slow. I noticed this warning 
```WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.2.2+cu118 with CUDA 1108 (you have 2.2.2+cu121)
    Python  3.10.14 (you have 3.10.14)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
``` 
and it seems important since the motion module uses memory efficient attention. 

I visited https://github.com/facebookresearch/xformers and re-installed as `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`, but then pip gave this warning: 
```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
hallo 0.1.0 requires torch==2.2.2, but you have torch 2.3.0+cu121 which is incompatible.
hallo 0.1.0 requires xformers==0.0.25.post1, but you have xformers 0.0.26.post1 which is incompatible.
torchvision 0.17.2+cu121 requires torch==2.2.2, but you have torch 2.3.0+cu121 which is incompatible.
Successfully installed nvidia-nccl-cu12-2.20.5 torch-2.3.0+cu121 triton-2.3.0 xformers-0.0.26.post1
```

After this, the inference code did not work anymore: 
```miniconda3/envs/hallo/lib/python3.10/site-packages/torch/_library/abstract_impl.py", line 30, in register
    if torch._C._dispatch_has_kernel_for_dispatch_key(self.qualname, "Meta"):
RuntimeError: operator torchvision::nms does not exist
```

Finally, I tried replacing `xformers==0.0.25.post1` with `xformers==0.0.26.post1` in `requirements.txt`, but got the error `ERROR: Cannot install -r requirements.txt torch==2.2.2+cu121 and xformers==0.0.26.post1 because these package versions have conflicting dependencies.`

Do you have any suggestions? Will the inference be significantly faster if xformers is installed correctly?

**Comment by nitinmukesh** [comment]
@roudimit 
You will find the solution here
https://www.youtube.com/watch?v=TAAoOn3flLM

**Comment by roudimit** [comment]
Thanks, `pip3 install -U xformers --index-url` then `pip3 install -U torchvision` seems to work. Sadly the inference did not get much faster.
