### ISSUE TITLE
add lora

### ISSUE THREAD

**Issue by liemthanh-playgroundvina** [fudan-generative-vision/hallo#146]
I want to add LORA: https://huggingface.co/latent-consistency/lcm-lora-sdv1-5 into the pipeline. How to do it??

**Comment by liemthanh-playgroundvina** [comment]
i'm using scripts at ./scripts/inference.py

**Comment by crystallee-ai** [comment]
In fact, we have fine-tuned the SD1.5 weights, so directly using the SD1.5 lcm-lora weights might not be suitable. If you insist on using them, you may consider fine-tuning them.

**Comment by liemthanh-playgroundvina** [comment]
Thanks for your assistance!
Also, do you have other methods or suggestions you might have for increasing the interface's speed?
I'm using 15steps that take 5 minutes for a 10s 512x512 video and it's too long to use.

**Comment by liemthanh-playgroundvina** [comment]
> > Thanks for your assistance! Also, do you have other methods or suggestions you might have for increasing the interface's speed? I'm using 15steps that take 5 minutes for a 10s 512x512 video and it's too long to use.
> 
> Is the result legit for 15 steps, what machine did you use for generation?

I'm using 3090ti with cu118+py3.9, the result is quite good with a little noise in the background

**Comment by liemthanh-playgroundvina** [comment]
https://github.com/fudan-generative-vision/hallo/assets/128352834/644b242f-baca-48b2-b4dc-b3b86f9a46e3

**Comment by crystallee-ai** [comment]
We have received a lot of issues about inference time, and we have plans to optimize it, but not in the near future. Thanks!
