### ISSUE TITLE
OOM error when loading models

### ISSUE THREAD

**Issue by tosunozgun** [fudan-generative-vision/hallo#15]
Hi,

when i try to test inference with 1 minute audio having oom error on ram, it seems some model files going to load on cpu.
my env is wsl2 ubuntu 20gb ram - rtx4090. detailed log is below

Some weights of Wav2VecModel were not initialized from the model checkpoint at ./pretrained_models/wav2vec/wav2vec2-base-960h and are newly initialized: ['wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'wav2vec2.encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'wav2vec2.masked_spec_embed']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:audio_separator.separator.separator:Separator version 0.17.2 instantiating with output_dir: ./.cache/audio_preprocess, output_format: WAV
INFO:audio_separator.separator.separator:Operating System: Linux #1 SMP Fri Mar 29 23:14:13 UTC 2024
INFO:audio_separator.separator.separator:System: Linux Node: developer Release: 5.15.153.1-microsoft-standard-WSL2 Machine: x86_64 Proc: x86_64
INFO:audio_separator.separator.separator:Python Version: 3.10.14
INFO:audio_separator.separator.separator:PyTorch Version: 2.2.2+cu121
INFO:audio_separator.separator.separator:FFmpeg installed: ffmpeg version N-115648-g7a3369398f Copyright (c) 2000-2024 the FFmpeg developers
INFO:audio_separator.separator.separator:ONNX Runtime CPU package installed with version: 1.18.0
INFO:audio_separator.separator.separator:CUDA is available in Torch, setting Torch device to CUDA
WARNING:audio_separator.separator.separator:CUDAExecutionProvider not available in ONNXruntime, so acceleration will NOT be enabled
INFO:audio_separator.separator.separator:Loading model Kim_Vocal_2.onnx...
INFO:audio_separator.separator.separator:Load model duration: 00:00:00
INFO:audio_separator.separator.separator:Starting separation process for audio_file_path: assets/derniere.wav
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 17/17 [00:16<00:00,  1.06it/s]
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 13/13 [00:00<00:00, 19.25it/s]
INFO:audio_separator.separator.separator:Saving Vocals stem to derniere_(Vocals)_Kim_Vocal_2.wav...
INFO:audio_separator.separator.separator:Clearing input audio file paths, sources and stems...
INFO:audio_separator.separator.separator:Separation duration: 00:00:17
The config attributes {'center_input_sample': False, 'out_channels': 4} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Some weights of the model checkpoint were not used when initializing UNet2DConditionModel:
 ['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
INFO:hallo.models.unet_3d:loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5/unet ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from pretrained_models/motion_module/mm_sd_v15_v2.ckpt
INFO:hallo.models.unet_3d:Loaded 453.20928M-parameter motion module
loaded weight from  ./pretrained_models/hallo/net.pth
Traceback (most recent call last):
  File "/home/developer/projects/hallo/scripts/inference.py", line 375, in <module>
    inference_process(command_line_args)
  File "/home/developer/projects/hallo/scripts/inference.py", line 323, in inference_process
    pipeline_output = pipeline(
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/hallo/animate/face_animate.py", line 335, in __call__
    ref_image_latents = self.vae.encode(ref_image_tensor).latent_dist.mean
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 260, in encode
    h = self.encoder(x)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/diffusers/models/autoencoders/vae.py", line 143, in forward
    sample = self.conv_in(sample)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/developer/miniconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 192.00 MiB. GPU 0 has a total capacity of 23.99 GiB of which 17.16 GiB is free. Including non-PyTorch memory, this process has 17179869184.00 GiB memory in use. Of the allocated memory 5.09 GiB is allocated by PyTorch, and 132.88 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by daswer123** [comment]
Tried it on windows, memory utilization on 3090 is about 10-11 GB

RAM utilization over 12 GB, didn't look exactly but I think about 15 GB.

40 steps, 25 fps , 4 seconds of audio, took about 7 minutes to process

**Comment by Inferencer** [comment]
> Tried it on windows, memory utilization on 3090 is about 10-11 GB
> 
> RAM utilization over 12 GB, didn't look exactly but I think about 15 GB.
> 
> 40 steps, 25 fps , 4 seconds of audio, took about 7 minutes to process


What was your image input size?

I just finished uploading to HuggingFace spaces ZeroGPU (private) and got similar utilization the duration needs work or the users will timeout with their allotted free GPU usage so will keep it private on a L4 (24gb) for now

**Comment by daswer123** [comment]
> What was your image input size?

I thought the memory utilization depends on the image size, and initially I tested it at ~800x800, then for the sake of experiment I changed the size to 400x400 and memory utilization didn't decrease.

In the config settings the image size is 512x512, so I think that the reference image does not matter what size it is, because the internal algorithms themselves change the image size to 512x512.

**Comment by Inferencer** [comment]
Ok I'll open a separate issue related to speed later as I accidently hijacked a OOM issue

**Comment by AricGamma** [comment]
Since there has been no further feedback, this issue will be closed. If needed, please reopen it.
