### ISSUE TITLE
Inference效果一般，没有样例的好，对图片的大小分辨率，有要求吧？

### ISSUE THREAD

**Issue by niubanxian** [fudan-generative-vision/hallo#16]
Inference效果一般，没有样例的好，对图片的大小分辨率，有要求吧？

**Comment by AIGC-Dancer** [comment]
能发一下你的测试数据吗？

**Comment by AricGamma** [comment]
我们提供了一些数据的样例

**Comment by AricGamma** [comment]
现在对输入数据有一些简单的要求，参考这里 https://github.com/fudan-generative-vision/hallo?tab=readme-ov-file#prepare-inference-data

另外音频需要是英文，目前还没有在其他语言上训练过。这里有一些数据样例 https://github.com/fudan-generative-vision/hallo/tree/main/examples

**Comment by AricGamma** [comment]
Closing this issue. If you have other questions, please reopen it.
