### ISSUE TITLE
sync-c和sync-d评价指标如何计算

### ISSUE THREAD

**Issue by hnsywangxin** [fudan-generative-vision/hallo#182]
感谢作者的开源！
目前我看了论文和代码，好像没有讲这2个指标是如何计算的，论文也没看到引用的出处，在网上也没看到相关指标计算的方式。
我个人猜测，咱们的这两个计算方式应该是跟wav2lip论文中的lse-c和lse-d指标是一致的。如果我理解的有问题，恳请作者指导一下如何计算这两个指标。
谢谢！

**Comment by crystallee-ai** [comment]
Thanks for your attention! We refer to the implementation of this repo: https://github.com/joonson/syncnet_python

**Comment by hnsywangxin** [comment]
> Thanks for your attention! We refer to the implementation of this repo: https://github.com/joonson/syncnet_python

了解了，谢谢
