### ISSUE TITLE
请问这几个weight参数具体影响什么呢，我看不太出来

### ISSUE THREAD

**Issue by wangqiaoch** [fudan-generative-vision/hallo#201]
pose weight ， face weight ， lip weight 和 face expand ratio，具体都影响什么呀，或者更大会怎么样，更小会怎么样，我调试了一个lip weight，并不能看出有什么区别呀

**Comment by xumingw** [comment]
三个weight主要会影响表现幅度    face expand ratio会影响脸部运动范围
