### ISSUE TITLE
HTTPSConnectionPool(host='raw.githubusercontent.com', port=443)

### ISSUE THREAD

**Issue by anstonjie** [fudan-generative-vision/hallo#22]
运行这个命令 > python scripts/inference.py --source_image ./examples/reference_images/1.jpg --driving_audio ./examples/driving_audios/1.wav

出现 requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/main/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x00000233F5201A50>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))

这个错误 需要科学上网吗？

**Comment by crystallee-ai** [comment]
如果你忽视这个错误，程序应该也可以正常运行的。如果不能正常运行，可以提供更多的报错信息么？

**Comment by anstonjie** [comment]
Traceback (most recent call last):
  File "D:\ai3\hallo\scripts\inference.py", line 372, in <module>
    inference_process(command_line_args)
  File "D:\ai3\hallo\scripts\inference.py", line 172, in inference_process
    with AudioProcessor(
  File "D:\ai3\hallo\venv\lib\site-packages\hallo\datasets\audio_processor.py", line 66, in __init__
    self.audio_separator.load_model(audio_separator_model_name)
  File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 616, in load_model
    model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename)
  File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 389, in download_model_files
    supported_model_files_grouped = self.list_supported_model_files()
  File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 304, in list_supported_model_files
    self.download_file_if_not_exists("https://raw.githubusercontent.com/TRvlvr/application_data/main/filelists/download_checks.json", download_checks_path)
  File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 284, in download_file_if_not_exists
    response = requests.get(url, stream=True, timeout=300)
  File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "D:\ai3\hallo\venv\lib\site-packages\requests\adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/main/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017CA0545C00>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)"))
(venv) PS D:\ai3\hallo>


执行到这里就不动了

**Comment by min-star** [comment]
the same problem

**Comment by min-star** [comment]
> Traceback (most recent call last): File "D:\ai3\hallo\scripts\inference.py", line 372, in inference_process(command_line_args) File "D:\ai3\hallo\scripts\inference.py", line 172, in inference_process with AudioProcessor( File "D:\ai3\hallo\venv\lib\site-packages\hallo\datasets\audio_processor.py", line 66, in **init** self.audio_separator.load_model(audio_separator_model_name) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 616, in load_model model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 389, in download_model_files supported_model_files_grouped = self.list_supported_model_files() File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 304, in list_supported_model_files self.download_file_if_not_exists("https://raw.githubusercontent.com/TRvlvr/application_data/main/filelists/download_checks.json", download_checks_path) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 284, in download_file_if_not_exists response = requests.get(url, stream=True, timeout=300) File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 73, in get return request("get", url, params=params, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\adapters.py", line 700, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/main/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017CA0545C00>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)")) (venv) PS D:\ai3\hallo>
> 
> 执行到这里就不动了
I solved the problem!
`wget -O pretrained_models/audio_separator/mdx_model_data.json https://github.com/TRvlvr/application_data/blob/main/mdx_model_data/model_data_new.json

wget -O pretrained_models/audio_separator/download_checks.json https://github.com/TRvlvr/application_data/blob/main/filelists/download_checks.json

wget -O pretrained_models/audio_separator/vr_data_new.json https://github.com/TRvlvr/application_data/blob/main/vr_model_data/model_data_new.json`

**Comment by min-star** [comment]
> Traceback (most recent call last): File "D:\ai3\hallo\scripts\inference.py", line 372, in inference_process(command_line_args) File "D:\ai3\hallo\scripts\inference.py", line 172, in inference_process with AudioProcessor( File "D:\ai3\hallo\venv\lib\site-packages\hallo\datasets\audio_processor.py", line 66, in **init** self.audio_separator.load_model(audio_separator_model_name) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 616, in load_model model_filename, model_type, model_friendly_name, model_path, yaml_config_filename = self.download_model_files(model_filename) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 389, in download_model_files supported_model_files_grouped = self.list_supported_model_files() File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 304, in list_supported_model_files self.download_file_if_not_exists("https://raw.githubusercontent.com/TRvlvr/application_data/main/filelists/download_checks.json", download_checks_path) File "D:\ai3\hallo\venv\lib\site-packages\audio_separator\separator\separator.py", line 284, in download_file_if_not_exists response = requests.get(url, stream=True, timeout=300) File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 73, in get return request("get", url, params=params, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\api.py", line 59, in request return session.request(method=method, url=url, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 589, in request resp = self.send(prep, **send_kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\sessions.py", line 703, in send r = adapter.send(request, **kwargs) File "D:\ai3\hallo\venv\lib\site-packages\requests\adapters.py", line 700, in send raise ConnectionError(e, request=request) requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /TRvlvr/application_data/main/filelists/download_checks.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000017CA0545C00>: Failed to resolve 'raw.githubusercontent.com' ([Errno 11004] getaddrinfo failed)")) (venv) PS D:\ai3\hallo>
> 
> 执行到这里就不动了
I solved the problem


wget -O pretrained_models/audio_separator/mdx_model_data.json https://github.com/TRvlvr/application_data/blob/main/mdx_model_data/model_data_new.json

wget -O pretrained_models/audio_separator/download_checks.json https://github.com/TRvlvr/application_data/blob/main/filelists/download_checks.json

wget -O pretrained_models/audio_separator/vr_data_new.json https://github.com/TRvlvr/application_data/blob/main/vr_model_data/model_data_new.json

**Comment by AricGamma** [comment]
Missing model config files for audio_separator and I have uploaded on Huggingface.

**Comment by AricGamma** [comment]
Closing this issue. If any futher questions, open a new one.
