### ISSUE TITLE
Windows inference

### ISSUE THREAD

**Issue by hexdrx** [fudan-generative-vision/hallo#24]
Hello everyone!
Can I run it on windows machine?

**Comment by Inferencer** [comment]
> Hello everyone! Can I run it on windows machine?

Yeah there is a windows fork

**Comment by AricGamma** [comment]
Duplicate of #39

**Comment by yjktech** [comment]
thx for sharing

**Comment by AricGamma** [comment]
We've tested on Windows 11, Cuda 12.1. It works well.
