### ISSUE TITLE
The inference code silently halts sometimes

### ISSUE THREAD

**Issue by cocktailpeanut** [fudan-generative-vision/hallo#31]
when running the inference code, especially when i'm trying to create a longer video (40sec or more) it often just halts along the way (sometimes halfway through, sometimes when it's almost done) silently.

there are no error messages when this happens, it simply halts the program altogether without any error message. anyone have this problem too? From my experience it happens around 30% of the time. i am looking at the task manager and I don't see anything out of the ordinary.

**Comment by AricGamma** [comment]
Could you provide the steps to reproduce the issue?

**Comment by AricGamma** [comment]
Since there has been no further feedback, this issue will be closed. If needed, please reopen it.
