### ISSUE TITLE
Is there an option to reduce the resolution?

### ISSUE THREAD

**Issue by samreid** [fudan-generative-vision/hallo#32]
The paper showed a dramatically faster inference rate for smaller resolution image processing. I tried reducing the input image size (half width and half height), but this did not seem to significantly improve the inference time. Do I need to change the code or add an option to change the image size during inference?

**Comment by xumingw** [comment]
configs/inference/default.yaml

**Comment by samreid** [comment]
Excellent, thanks! Here's a link for my records. https://github.com/fudan-generative-vision/hallo/blob/6a3e6e355b4ad006d08ed78bdfe85493febe92d3/configs/inference/default.yaml 

This issue can be closed.
