### ISSUE TITLE
Minimum VRAM?

### ISSUE THREAD

**Issue by yuesam** [fudan-generative-vision/hallo#34]
What's the min vram for this? Thanks!

**Comment by jryebread** [comment]
+1 Same Question, Tried to run on an A10G with 24GB VRAM and got `onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/1k3d68.onnx failed:Protobuf parsing failed.` Think the model too big to load?

**Comment by oisilener1982** [comment]
i was able to run this with rtx 3080 10gb. You just need to lower the resolution to 448. It would take forever to generate if the default 512 is used.

**Comment by nitinmukesh** [comment]
I am testing on RTX4060 8 GB and it is not able to use full VRAM. The only problem is it does not show how much is remaining, just going on endlessely for 7 hours 

<img width="1265" alt="image" src="https://github.com/fudan-generative-vision/hallo/assets/2102186/07e1568e-3e63-4dc8-acbf-068e7ccd836b">

**Comment by AricGamma** [comment]
it cost about 9G VRAM at runtime.

**Comment by AricGamma** [comment]
> +1 Same Question, Tried to run on an A10G with 24GB VRAM and got `onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/1k3d68.onnx failed:Protobuf parsing failed.` Think the model too big to load?

That may be another problem. please open a new issue.

**Comment by AricGamma** [comment]
> +1 Same Question, Tried to run on an A10G with 24GB VRAM and got `onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./pretrained_models/face_analysis/models/1k3d68.onnx failed:Protobuf parsing failed.` Think the model too big to load?

Maybe the model is incomplete. Refer to #42
