### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by JZArray** [fudan-generative-vision/hallo#35]
Hello guys, nice work! But I have a problem while running the demo.

loaded weight from  ./pretrained_models/hallo/net.pth
Segmentation fault (core dumped)

How do I solve this issue?

Thanks in advance!

**Comment by JZArray** [comment]
> Could you please provide more details about the error?

Some weights of the model checkpoint were not used when initializing UNet2DConditionModel: 
 ['conv_norm_out.bias, conv_norm_out.weight, conv_out.bias, conv_out.weight']
INFO:hallo.models.unet_3d:loaded temporal unet's pretrained weights from pretrained_models/stable-diffusion-v1-5/unet ...
The config attributes {'center_input_sample': False} were passed to UNet3DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
Load motion module params from pretrained_models/motion_module/mm_sd_v15_v2.ckpt
INFO:hallo.models.unet_3d:Loaded 453.20928M-parameter motion module
loaded weight from  ./pretrained_models/hallo/net.pth
Fatal Python error: Segmentation fault

Thread 0x00007f0ec00ff640 (most recent call first):
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/threading.py", line 324 in wait
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/threading.py", line 600 in wait
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/tqdm/_monitor.py", line 60 in run
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/threading.py", line 1009 in _bootstrap_inner
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/threading.py", line 966 in _bootstrap

Current thread 0x00007f126a8fa740 (most recent call first):
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456 in _conv_forward
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460 in forward
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/hallo/models/resnet.py", line 63 in forward
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520 in _call_impl
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511 in _wrapped_call_impl
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/hallo/models/face_locator.py", line 108 in forward
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520 in _call_impl
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511 in _wrapped_call_impl
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/hallo/animate/face_animate.py", line 342 in __call__
  File "/xxxx/anaconda3/envs/hallo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115 in decorate_context
  File "/xxxx/hallo-main/scripts/inference.py", line 327 in inference_process
  File "/xxxx/hallo-main/scripts/inference.py", line 379 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, charset_normalizer.md, requests.packages.charset_normalizer.md, requests.packages.chardet.md, yaml._yaml, PIL._imaging, google._upb._message, scipy._lib._ccallback_c, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.linalg._propack._spropack, scipy.sparse.linalg._propack._dpropack, scipy.sparse.linalg._propack._cpropack, scipy.sparse.linalg._propack._zpropack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.special._ufuncs_cxx, scipy.special._cdflib, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, scipy.spatial.transform._rotation, scipy.optimize._direct, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, regex._regex, av._core, av.logging, av.bytesource, av.buffer, av.audio.format, av.enum, av.error, av.utils, av.option, av.descriptor, av.container.pyio, av.dictionary, av.format, av.stream, av.container.streams, av.sidedata.motionvectors, av.sidedata.sidedata, av.packet, av.container.input, av.container.output, av.container.core, av.codec.context, av.video.format, av.video.reformatter, av.plane, av.video.plane, av.video.frame, av.video.stream, av.codec.codec, av.frame, av.audio.layout, av.audio.plane, av.audio.frame, av.audio.stream, av.audio.fifo, av.filter.pad, av.filter.link, av.filter.context, av.filter.graph, av.filter.filter, av.audio.resampler, av.bitstream, kiwisolver._cext, _cffi_backend, PIL._imagingft, skimage._shared.geometry, scipy.ndimage._nd_image, _ni_label, scipy.ndimage._ni_label, sklearn.__check_build._check_build, psutil._psutil_linux, psutil._psutil_posix, scipy.special.cython_special, scipy.stats._stats, scipy.stats.beta_ufunc, scipy.stats._boost.beta_ufunc, scipy.stats.binom_ufunc, scipy.stats._boost.binom_ufunc, scipy.stats.nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, scipy.stats.ncf_ufunc, scipy.stats._boost.ncf_ufunc, scipy.stats.ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, scipy.stats.nct_ufunc, scipy.stats._boost.nct_ufunc, scipy.stats.skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, scipy.stats.invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy._lib._uarray._uarray, scipy.stats._ansari_swilk_statistics, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, scipy.stats._unuran.unuran_wrapper, sklearn.utils._isfinite, sklearn.utils.sparsefuncs_fast, sklearn.utils.murmurhash, sklearn.utils._openmp_helpers, sklearn.utils._random, sklearn.utils._seq_dataset, sklearn.metrics.cluster._expected_mutual_info_fast, sklearn.preprocessing._csr_polynomial_expansion, sklearn.preprocessing._target_encoder_fast, sklearn.metrics._dist_metrics, sklearn.metrics._pairwise_distances_reduction._datasets_pair, sklearn.utils._cython_blas, sklearn.metrics._pairwise_distances_reduction._base, sklearn.metrics._pairwise_distances_reduction._middle_term_computer, sklearn.utils._heap, sklearn.utils._sorting, sklearn.metrics._pairwise_distances_reduction._argkmin, sklearn.metrics._pairwise_distances_reduction._argkmin_classmode, sklearn.utils._vector_sentinel, sklearn.metrics._pairwise_distances_reduction._radius_neighbors, sklearn.metrics._pairwise_distances_reduction._radius_neighbors_classmode, sklearn.metrics._pairwise_fast, sklearn.linear_model._cd_fast, _loss, sklearn._loss._loss, sklearn.utils.arrayfuncs, sklearn.svm._liblinear, sklearn.svm._libsvm, sklearn.svm._libsvm_sparse, sklearn.utils._weight_vector, sklearn.linear_model._sgd_fast, sklearn.linear_model._sag_fast, sklearn.decomposition._online_lda_fast, sklearn.decomposition._cdnmf_fast, skimage.measure._ccomp, insightface.thirdparty.face3d.mesh.cython.mesh_core_cython, scipy.io.matlab._mio_utils, scipy.io.matlab._streams, scipy.io.matlab._mio5_utils, PIL._imagingmath, scipy.signal._sigtools, scipy.signal._max_len_seq_inner, scipy.signal._upfirdn_apply, scipy.signal._spline, scipy.signal._sosfilt, scipy.signal._spectral, scipy.signal._peak_finding_utils, soxr.cysoxr, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, msgpack._cmsgpack (total: 236)
Segmentation fault (core dumped)

**Comment by subazinga** [comment]
Which GPU do you use? And can you also list the version of all packages?

**Comment by JZArray** [comment]
I am using A100.
absl-py                   2.1.0                     <pip>
accelerate                0.28.0                    <pip>
albucore                  0.0.11                    <pip>
albumentations            1.4.8                     <pip>
alembic                   1.13.1                    <pip>
aniso8601                 9.0.1                     <pip>
anna                      0.1.0                     <pip>
annotated-types           0.7.0                     <pip>
antlr4-python3-runtime    4.9.3                     <pip>
astroid                   3.2.2                     <pip>
attrs                     23.2.0                    <pip>
audio-separator           0.17.2                    <pip>
audioread                 3.0.1                     <pip>
av                        12.1.0                    <pip>
beartype                  0.18.5                    <pip>
bitsandbytes              0.43.1                    <pip>
blinker                   1.8.2                     <pip>
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2024.3.11            h06a4308_0    defaults
cachetools                5.3.3                     <pip>
certifi                   2024.6.2                  <pip>
cffi                      1.16.0                    <pip>
cfgv                      3.4.0                     <pip>
charset-normalizer        3.3.2                     <pip>
click                     8.1.7                     <pip>
cloudpickle               3.0.0                     <pip>
coloredlogs               15.0.1                    <pip>
contextlib2               21.6.0                    <pip>
contourpy                 1.2.1                     <pip>
cycler                    0.12.1                    <pip>
Cython                    3.0.10                    <pip>
decorator                 4.4.2                     <pip>
decord                    0.6.0                     <pip>
Deprecated                1.2.14                    <pip>
diffq                     0.2.4                     <pip>
diffusers                 0.27.2                    <pip>
dill                      0.3.8                     <pip>
distlib                   0.3.8                     <pip>
docker                    7.1.0                     <pip>
easydict                  1.13                      <pip>
einops                    0.8.0                     <pip>
entrypoints               0.4                       <pip>
filelock                  3.15.1                    <pip>
Flask                     3.0.3                     <pip>
flatbuffers               24.3.25                   <pip>
fonttools                 4.53.0                    <pip>
fsspec                    2024.6.0                  <pip>
gitdb                     4.0.11                    <pip>
GitPython                 3.1.43                    <pip>
graphene                  3.3                       <pip>
graphql-core              3.2.3                     <pip>
graphql-relay             3.2.0                     <pip>
greenlet                  3.0.3                     <pip>
gunicorn                  22.0.0                    <pip>
huggingface-hub           0.23.4                    <pip>
humanfriendly             10.0                      <pip>
identify                  2.5.36                    <pip>
idna                      3.7                       <pip>
imageio                   2.34.1                    <pip>
imageio-ffmpeg            0.5.1                     <pip>
importlib_metadata        7.1.0                     <pip>
insightface               0.7.3                     <pip>
isort                     5.13.2                    <pip>
itsdangerous              2.2.0                     <pip>
jax                       0.4.29                    <pip>
jaxlib                    0.4.29                    <pip>
Jinja2                    3.1.4                     <pip>
joblib                    1.4.2                     <pip>
julius                    0.2.7                     <pip>
kiwisolver                1.4.5                     <pip>
lazy_loader               0.4                       <pip>
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
librosa                   0.10.2.post1              <pip>
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
llvmlite                  0.43.0                    <pip>
Mako                      1.3.5                     <pip>
Markdown                  3.6                       <pip>
MarkupSafe                2.1.5                     <pip>
matplotlib                3.9.0                     <pip>
mccabe                    0.7.0                     <pip>
mediapipe                 0.10.14                   <pip>
ml-dtypes                 0.4.0                     <pip>
ml_collections            0.1.1                     <pip>
mlflow                    2.13.1                    <pip>
moviepy                   1.0.3                     <pip>
mpmath                    1.3.0                     <pip>
msgpack                   1.0.8                     <pip>
ncurses                   6.3                  h7f8727e_2    defaults
networkx                  3.3                       <pip>
nodeenv                   1.9.1                     <pip>
numba                     0.60.0                    <pip>
numpy                     1.26.4                    <pip>
nvidia-cublas-cu12        12.1.3.1                  <pip>
nvidia-cuda-cupti-cu12    12.1.105                  <pip>
nvidia-cuda-nvrtc-cu12    12.1.105                  <pip>
nvidia-cuda-runtime-cu12  12.1.105                  <pip>
nvidia-cudnn-cu12         8.9.2.26                  <pip>
nvidia-cufft-cu12         11.0.2.54                 <pip>
nvidia-curand-cu12        10.3.2.106                <pip>
nvidia-cusolver-cu12      11.4.5.107                <pip>
nvidia-cusparse-cu12      12.1.0.106                <pip>
nvidia-nccl-cu12          2.19.3                    <pip>
nvidia-nvjitlink-cu12     12.5.40                   <pip>
nvidia-nvtx-cu12          12.1.105                  <pip>
omegaconf                 2.3.0                     <pip>
onnx                      1.16.1                    <pip>
onnx2torch                1.5.14                    <pip>
onnxruntime               1.18.0                    <pip>
opencv-contrib-python     4.9.0.80                  <pip>
opencv-python             4.9.0.80                  <pip>
opencv-python-headless    4.9.0.80                  <pip>
openssl                   1.1.1w               h7f8727e_0    defaults
opentelemetry-api         1.25.0                    <pip>
opentelemetry-sdk         1.25.0                    <pip>
opentelemetry-semantic-conventions 0.46b0                    <pip>
opt-einsum                3.3.0                     <pip>
packaging                 24.1                      <pip>
pandas                    2.2.2                     <pip>
pillow                    10.3.0                    <pip>
pip                       24.0            py310h06a4308_0    defaults
pip                       24.0                      <pip>
platformdirs              4.2.2                     <pip>
pooch                     1.8.2                     <pip>
pre-commit                3.7.1                     <pip>
prettytable               3.10.0                    <pip>
proglog                   0.1.10                    <pip>
protobuf                  4.25.3                    <pip>
psutil                    5.9.8                     <pip>
pyarrow                   15.0.2                    <pip>
pycparser                 2.22                      <pip>
pydantic                  2.7.4                     <pip>
pydantic_core             2.18.4                    <pip>
pydub                     0.25.1                    <pip>
pylint                    3.2.2                     <pip>
pyparsing                 3.1.2                     <pip>
python                    3.10.4               h12debd9_0    defaults
python-dateutil           2.9.0.post0               <pip>
pytz                      2024.1                    <pip>
PyYAML                    6.0.1                     <pip>
querystring-parser        1.2.4                     <pip>
readline                  8.1.2                h7f8727e_1    defaults
regex                     2024.5.15                 <pip>
requests                  2.32.3                    <pip>
resampy                   0.4.3                     <pip>
rotary-embedding-torch    0.6.2                     <pip>
safetensors               0.4.3                     <pip>
samplerate                0.1.0                     <pip>
scikit-image              0.23.2                    <pip>
scikit-learn              1.5.0                     <pip>
scipy                     1.13.1                    <pip>
setuptools                69.5.1          py310h06a4308_0    defaults
setuptools                70.0.0                    <pip>
six                       1.16.0                    <pip>
smmap                     5.0.1                     <pip>
sounddevice               0.4.7                     <pip>
soundfile                 0.12.1                    <pip>
soxr                      0.3.7                     <pip>
SQLAlchemy                2.0.30                    <pip>
sqlite                    3.38.5               hc218d9a_0    defaults
sqlparse                  0.5.0                     <pip>
sympy                     1.12.1                    <pip>
threadpoolctl             3.5.0                     <pip>
tifffile                  2024.5.22                 <pip>
tk                        8.6.12               h1ccaba5_0    defaults
tokenizers                0.15.2                    <pip>
tomli                     2.0.1                     <pip>
tomlkit                   0.12.5                    <pip>
torch                     2.2.2                     <pip>
torchvision               0.17.2                    <pip>
tqdm                      4.66.4                    <pip>
transformers              4.39.2                    <pip>
triton                    2.2.0                     <pip>
typing_extensions         4.12.2                    <pip>
tzdata                    2024.1                    <pip>
tzdata                    2024a                h04d1e81_0    defaults
urllib3                   2.2.1                     <pip>
virtualenv                20.26.2                   <pip>
wcwidth                   0.2.13                    <pip>
Werkzeug                  3.0.3                     <pip>
wheel                     0.43.0          py310h06a4308_0    defaults
wheel                     0.43.0                    <pip>
wrapt                     1.16.0                    <pip>
xformers                  0.0.25.post1              <pip>
xz                        5.2.5                h7f8727e_1    defaults
zipp                      3.19.2                    <pip>
zlib                      1.2.12               h7f8727e_2    defaults


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0


CUDA Version: 12.2

@subazinga @xumingw

**Comment by JZArray** [comment]
solved

**Comment by gtfaiwxm** [comment]
how to solve the problem?

**Comment by JZArray** [comment]
> how to solve the problem?

@gtfaiwxm I use torch-1.12, then it can work. I think it is due to the conflict between my CUDA(11.x) and torch 2.0.x in my case.

**Comment by gtfaiwxm** [comment]
Thanks.
