### ISSUE TITLE
Windows 10 - no luck.

### ISSUE THREAD

**Issue by VitaliyAT** [fudan-generative-vision/hallo#39]
[cmd.log](https://github.com/user-attachments/files/15866395/cmd.log)
You can see that install instraction is not full. All of this can be scripted, Problem with Triton was solved, but no luck finally. Can't digg so deep in python code. So maybe it would be helpfull for people who will go after me.

**Comment by Echolink50** [comment]
Maybe try this windows branch. https://github.com/sdbds/hallo-for-windows
I haven't tried it but maybe there's some difference

**Comment by AricGamma** [comment]
Hi, we have fixed dependencies' issue on Windows and it works well. Please pull the latest version and have a try.

**Comment by subazinga** [comment]
I will close this issue. You can reopen it if you have any other questions.
