### ISSUE TITLE
生成的视频比音频短，有时候漏掉了最后的一点，像是被切断了

### ISSUE THREAD

**Issue by yeeyou** [fudan-generative-vision/hallo#41]
这是输入的音频信息
Duration: 00:00:09.56, bitrate: 705 kb/s

这是生成的视频信息
Duration: 00:00:09.00, start: 0.000000, bitrate: 794 kb/s

视频文件 最后的twice感觉是漏掉了
https://github.com/fudan-generative-vision/hallo/assets/775190/b781f8ca-32fd-4c89-9c9f-0c3e69b85bd4

**Comment by subazinga** [comment]
这个是已知问题，我们会尽快修复。我们在处理最后一个clip时如果长度不够会drop掉。可以先尝试多增加一些音频片段以避免该问题。
