### ISSUE TITLE
IndexError: cannot do a non-empty take from an empty axes.

### ISSUE THREAD

**Issue by JaylenTang** [fudan-generative-vision/hallo#7]
Hi there,

Thanks for sharing this work, it looks perfect!

After following the setup instructions,  when I trying to run

”python scripts/inference.py --source_image 1.png --driving_audio 1.wav"

 I got an issue like: 

<img width="1241" alt="image" src="https://github.com/fudan-generative-vision/hallo/assets/111931401/3b527fd9-83bc-4323-9a8f-19a831bf0ff7">

 I would appreciate it if you would help.
 
 Regards,

**Comment by subazinga** [comment]
You should specify the output path, by `--output`. I think the path of default value does not exist in your environment.

**Comment by AricGamma** [comment]
It appears that CUDA is not installed on your system. You can verify this by running nvcc --version.

**Comment by JaylenTang** [comment]
> It appears that CUDA is not installed on your system. You can verify this by running `nvcc --version`.

<img width="394" alt="image" src="https://github.com/fudan-generative-vision/hallo/assets/111931401/6a22ebb4-27b2-4a76-a936-9ccf5799d6ef">

By the way, I think I have installed the CUDA before...

**Comment by AricGamma** [comment]
Can you find a `.cache` folder in your work root?

**Comment by JaylenTang** [comment]
> Can you find a `.cache` folder in your work root?

https://github.com/fudan-generative-vision/champ/issues/95#issuecomment-2078111761

solved! thanks~
