### ISSUE TITLE
推理出来的视频背景有一些移动的奇怪噪斑

### ISSUE THREAD

**Issue by s3219521aa** [fudan-generative-vision/hallo#73]
推理视频截图
![image](https://github.com/fudan-generative-vision/hallo/assets/36285143/dba80a51-9bd8-41b6-a4d8-8bc27a8280ef)
原图
![image](https://github.com/fudan-generative-vision/hallo/assets/36285143/cd921dca-8d7c-412b-8906-3aba04249145)

**Comment by jasonisme123** [comment]
很可能是因为使用了SD

**Comment by subazinga** [comment]
我们的方法在纯色背景的图像上偶尔会产生背景噪声，可以在非纯色背景的图像试试。
