### ISSUE TITLE
checkpoint file removed?

### ISSUE THREAD

**Issue by kevincao8828** [fudan-generative-vision/hallo#82]
![image](https://github.com/fudan-generative-vision/hallo/assets/15197981/75e1f10d-3476-4aa6-88c4-98cd267e9f6b)
I was just cloning the checkpoint files, it run to error. When I check the files, it seems the old existing files are gone...

**Comment by AricGamma** [comment]
Sorry, we are re-uploading checkpoints to fix a hash verification error. please wait a sec.

**Comment by kevincao8828** [comment]
OK, thx

**Comment by AricGamma** [comment]
It resumed now. please have a try. 
sorry for your trouble. If any other question, just let me know.
