### ISSUE TITLE
及其优秀的开源项目，是否能出一个comfyui的diffusion版本？

### ISSUE THREAD

**Issue by daoliangai** [fudan-generative-vision/hallo#95]
及其优秀的开源项目，直接使用音频生成说话视频而不是基于参考视频。不知道是不是可以将过程理解为通过频生成说话的面部动作，然后在使用类似controlnet的模型对生成的图像进行控制？
想来如果这个项目支持diffusion版本的话，应该有更多的有趣的用法。
尝试过自己拆解每个模型为单独的节点，但是自己不擅长python代码而且当前的AI编程类模型也实现不了这个功能。
所以期待能有一个diffusion版本。

**Comment by subazinga** [comment]
有开发者做了comfyui版本的Hallo，可以参考该[链接](https://github.com/AIFSH/ComfyUI-Hallo)。其他版本的可参见[链接](https://github.com/fudan-generative-vision/hallo?tab=readme-ov-file#-community-resources)。
