### ISSUE TITLE
Nice Job！but In terms of details, there is a sense of tearing and deformation on the lips and face. How can it be adjusted?

### ISSUE THREAD

**Issue by tf18536** [fudan-generative-vision/hallo#97]
![微信截图_20240626130433](https://github.com/fudan-generative-vision/hallo/assets/101076770/bbc04a40-ec3c-46ce-aa78-496205a06f32)
![微信截图_20240626130511](https://github.com/fudan-generative-vision/hallo/assets/101076770/411308fe-edba-4b89-9b58-1569a77f98e6)
>
![微信截图_20240626130311](https://github.com/fudan-generative-vision/hallo/assets/101076770/b041f198-689b-4a7b-930f-d60eca0ba0bb)
![微信截图_20240626130328](https://github.com/fudan-generative-vision/hallo/assets/101076770/c3a79168-5d68-4826-864b-b94aee30f095)

**Comment by subazinga** [comment]
The provided image should be in a square shape, or the method may produce unexpected results.
